name: Fuzzing

on:  
  pull_request:
  # We use two branches here test and release; We make no use of main here
    branches: ["release", "test"]

jobs:     
  test:
    name: Test
    runs-on: ubuntu-latest
    # Execute when the a PR is done on this target branch 
    if: github.base_ref == 'test'
    steps:
    #checkout this github to work with
      - uses: actions/checkout@main   
      # Compile it using the libfuzz library
      - name: Clang++
        run: clang++ -g -fsanitize=fuzzer fuzz_me.cc        
      # Run it for 10 minutes
      - name: Execute
        run: ./a.out -max_total_time=600
    
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.base_ref == 'release'
    steps:
      - uses: actions/checkout@main      
      - name: Clang++
      # Compile it using libfuzz library and Address Sanitizer
        run: clang++ -g -fsanitize=address,fuzzer fuzz_me.cc        
      - name: Execute
        run: ./a.out -max_total_time=600
