# This is a basic workflow to help you get started with Actions

name: Fuzzing

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:     
  Fuzz:    
    runs-on: ubuntu-latest     
    steps:
      - uses: actions/checkout@main
      - name: Clang++
        run: clang++ -g -fsanitize=address,fuzzer fuzz_me.cc     
      - name: Execute
        run: ./a.out -max_total_time=90
