# This is a basic workflow to help you get started with Actions

name: Fuzzing

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:     
  Fuzz:    
    runs-on: ubuntu-latest 
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - name: Clang++
        run: clang++ -g -fsanitize=fuzzer fuzz_me.cc     
      - name: Execute
        run: ./a.out
